"""add announcements table

Revision ID: 566b87119787
Revises: e81d5411b056
Create Date: 2026-08-14 08:29:48.495014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '566b87119787'
down_revision: Union[str, Sequence[str], None] = 'e81d5411b056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'event_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('posts', 'short_content',
               existing_type=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='short contenrsdfsdfg')
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('posts', 'short_content',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='short contenrsdfsdfg')
    op.alter_column('calendar_events', 'event_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
